language: python

stages:
  - test
  - deploy

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

dist: xenial
    
install:
  - cd py_bind
  - pip install -r requirements.txt
  - python setup.py prepare
  - python setup.py install

script:
  - cd test
  - nosetests --verbose

after_success:
  - $PIP install cibuildwheel==0.10.2
  - cibuildwheel --output-dir wheelhouse
  - ls -l wheelhouse
