language: python

env:
  global:
    - CIBW_BEFORE_BUILD="pip install -r requirements.txt && python setup.py prepare"

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - CIBW_SKIP=*manylinux1_i686* 
        - PIP=pip
    - os: osx
      language: generic
      env: 
        - PIP=pip2

script:
  - $PIP install cibuildwheel==0.10.2
  - cibuildwheel py_bind --output-dir wheelhouse
