language: python

stages:
  - test
  - deploy

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

dist: xenial
    
install:
  - cd py_bind
  - pip install -r requirements.txt
  - python setup.py prepare
  - python setup.py install

script:
  - cd test
  - nosetests --verbose

jobs:
  include:
    - stage: deploy
      script: echo Deploy is here

