language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y git
  - sudo apt install python-pip
  - pip install --upgrade pip
  - pip install numpy
  - pip install cython
  - pip install pyyaml
  - pip install nose
  
install: true

script:
  - cd py_bind
  - python setup.py prepare
  - python setup.py install
  - cd test
  - nosetests --verbose
