language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - cd py_bind
  - pip install -r requirements.txt
  - python setup.py prepare
  - python setup.py install

script:
  - cd test
  - nosetests --verbose

