language: python
matrix:
  include:
  - sudo: required
    services:
    - docker
    env:
    - CIBW_SKIP="*manylinux1_i686* cp34-* cp36-* cp35-*"
    - CIBW_BEFORE_BUILD="pip install -r requirements.txt && python setup.py prepare
      --liboptv-dir liboptv-src"
    - PIP=pip
  #- os: osx
  #  language: generic
  #  env:
  #  - PIP=pip2
  #  - CIBW_BEFORE_BUILD="cd py_bind && pip install -r requirements.txt && python setup.py
  #    prepare --liboptv-dir liboptv-src"
  #  - CIBW_SKIP=cp34-*
script:
- "$PIP install cibuildwheel==0.10.2"
- cp -R liboptv py_bind/liboptv-src
- cibuildwheel py_bind --output-dir wheelhouse

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "optv"
  skip_cleanup: true
  local_dir: wheelhouse
  on:
    branch: travis
