language: python

matrix:
  include:
    - python: "2.7"
    - env: DEPS="numpy cython pyyaml nose" BUILD_DOCS=false SKIP_SLOW=true

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  
install:
  - conda update --yes conda
  - conda create -n testenv --yes $DEPS nose python=$TRAVIS_PYTHON_VERSION
  - source activate testenv

  # for debugging...
  - echo $PATH
  - which python
  - conda info
  - conda list

script:
  - cd py_bind
  - python setup.py prepare
  - python setup.py install
  - cd test
  - nosetests --verbose
