language: python
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y git
  
install: true

script:
- cd py_bind
- python setup.py prepare
- python setup.py install
- cd test
- pip install nose
- nosetests
