language: python

env:
  global:
    - CIBW_BEFORE_BUILD="pwd && pip install -r requirements.txt && python setup.py prepare --liboptv-dir liboptv-src"

matrix:
  include:
    # - sudo: required
    #  services:
    #    - docker
    #  env:
    #    - CIBW_SKIP=*manylinux1_i686* 
    #    - PIP=pip
    - os: osx
      language: generic
      env: 
        - PIP=pip2

script:
  - $PIP install cibuildwheel==0.10.2
  - cp -R liboptv py_bind/liboptv-src
  - cibuildwheel py_bind --output-dir wheelhouse
