language: python
matrix:
  include:
  - sudo: required
    services:
    - docker
    env:
    - CIBW_SKIP="*manylinux1_i686* cp34-* cp27-* cp35-* cp36-*"
    - CIBW_BEFORE_BUILD="pip install -r requirements.txt && python setup.py prepare
      --liboptv-dir liboptv-src"
    - PIP=pip
  #- os: osx
  #  language: generic
  #  env:
  #  - PIP=pip2
  #  - CIBW_BEFORE_BUILD="cd py_bind && pip install -r requirements.txt && python setup.py
  #    prepare --liboptv-dir liboptv-src"
  #  - CIBW_SKIP=cp34-*
script:
- "$PIP install cibuildwheel==0.10.2"
- cp -R liboptv py_bind/liboptv-src
- cibuildwheel py_bind --output-dir wheelhouse
before_deploy: echo 'start deploy'
deploy:
  provider: s3
  local_dir: wheelhouse
  skip_cleanup: true
  secure: X5TOhQpeoQ9yHfuFqUPZHP8bwaUEqG16xPtMXlTTxV+pmRKK7mw4xEXq8CUVu2OTtuvfDMdrdwlujQxOS5R27opdZPWZBl4yT1IlGHHXptUAJvxdmuEARxlUahsOM+Fse4KpcqAJLkypOUlRMwSd17SYwO58+69WBQxcXjNPLHpEuDdq3ED+tu8dCKgYYErjQFUrlCDZxUODCBpe/1t8r9n33/ufT6sFrMB0iW7yCPNBT6RXlGeHaC8K4ep6NjPFdky5evWk7oq/bw6O33FtVmgRGqHxC6gcf/H6MiYkiUsrIEQl7jfehNhL9eAkqL9nkVz2v8X6KjxITgQ5tI63RxGLsAxFzDF7SQ+zcSwNiag9w7O/ZrSKLqtrPv0SV2VoAdyqaY9JLtTvZugYJQXTafrp4+Rz8YzAKfQcG3Xf4iICqyxcM7ZolHy/27nRpoa/J3utziHB1AJcOgErg+fFMmdnukyATuLJS+sBvMSIazCXfoCBgccuwx3foosj4YaPiiGj8bY39OZW2MEA5e5pCWnQvqIzFwj3DHzaEcAdUaThFpGskFSFkVLHPr6xB8bDuTvgrJWlM+pWJfwY1SmzDFa+AVI+oaEbBr6SE33WBY0pCOw+y43+7/MyeTCND4gW08mNVpksfAnxenWiAwSpJumBwJpZAOE9jEvq2ButlcY=
  secure: LoO/weeESSwE3FM+49HmlFFCRvZL6VeBrXZsxWmmwaRQa2R8ll+PBviYX4SuwEydBmiNeNsRZ9IBZSe8fA/5xkOUewTxE6QTL2OB1VA0AmQUZmQBdFojPfJyO2CW/AHHrgxut/ZqhYVPlKSz0E4yIGcELXYftwDIJoJNQ3pvpTVbN/HOPpnX9i07hddn1Ar14atGY/GB0+dzjaKFe2JW46/bY43uboSqLECRpekXt1bH2hqlwhyh9NdzyYagJzhOjFNwG1lQ+tLVW6jKHf3sePXYPmPEzec9qE/G2mXrdr03a7brQV9wNLUhtrALYvN9unMBdG+my5oB1KASwJ3lbcRgj0ljBfDkyUYM1WCf8ZvWwfudcnU5oK6U/eiGbWzQey/KAhRgnGARXReW/sRp3g4yz6XgVh3jkjNEbSRXLoa+vr0OWJsY7UsdjWZ46dx4I3dM9/jLl6og2NDttxYlhVxwaW3qTUTFkhiBo5AZnPi+UtoLifyhDrQXwmFDOVYmR9cdYUBpb6jsnXqTmF0qauX5kYZt2xAICC+djcMEHvhIkYNk6wn4HyEe/hOTvgbIZ04d3CPpfmRFBjOx924jez/OkCAFYSma5X+ZA6iI6COfWqFHPmyJNf7k4fckQ/5ggfTS0OA+tzloA03iZNHNP8SnTf5lG2cAh11V9Deojns=
  on:
    branch: travis
